import WhatsAppIcon from './WhatsAppIcon'
export { ServiceCard, ServicesGrid, ProjectCard, PackagesSection } from './ConversionSections'
export { default as ContactForm } from './EnquiryForm'
import { useEffect, useState } from 'react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { ArrowDownRight, ArrowRight, ArrowUpRight, Menu, X, MoveUpRight, Sparkles, Layers3, ShoppingBag, Workflow, Figma, RefreshCw, ShieldCheck, PanelsTopLeft, CircleCheck, Zap, Compass, Code2, Rocket, LifeBuoy, Quote, Check, BriefcaseBusiness, Store, BadgeCheck, Database, FileCode2, Wind, GitBranch, Cloud, Server, Braces, Gauge, Smartphone } from 'lucide-react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { Helmet } from 'react-helmet-async'
import { services } from '../data/services'
import { projects } from '../data/projects'
import { testimonials } from '../data/testimonials'
import { packages } from '../data/packages'

const icons = { PanelsTopLeft, ShoppingBag, Workflow, Figma, RefreshCw, ShieldCheck }
const nav = [['Home','/'],['Services','/services'],['Work','/work'],['Pricing','/services#pricing'],['Contact','/contact']]
export function Logo({ light=false }) { return <Link to="/" className={`logo ${light?'logo-light':''}`} aria-label="Webstead home"><img src="/webstead-logo.jpg" alt="Webstead"/></Link> }
export function SEO({ title, description }) { const url = typeof window !== 'undefined' ? window.location.href : 'https://webstead.com/'; return <Helmet><title>{title}</title><meta name="description" content={description}/><meta property="og:title" content={title}/><meta property="og:description" content={description}/><meta property="og:type" content="website"/><meta property="og:url" content={url}/><link rel="canonical" href={url}/></Helmet> }
export function Navbar() { const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false); const location=useLocation(); useEffect(()=>{setOpen(false);if(!location.hash){window.scrollTo({top:0,behavior:'instant'});return}let attempts=0;const timer=window.setInterval(()=>{const target=document.getElementById(location.hash.slice(1));if(target){target.scrollIntoView({behavior:'instant',block:'start'});window.clearInterval(timer)}else if(++attempts>60)window.clearInterval(timer)},50);return()=>window.clearInterval(timer)},[location.pathname,location.hash]); useEffect(()=>{const f=()=>setScrolled(window.scrollY>18);window.addEventListener('scroll',f);return()=>window.removeEventListener('scroll',f)},[]); return <header className={`navbar ${scrolled?'scrolled':''}`}><div className="nav-inner wrap"><Logo/><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label,path])=><NavLink key={path} to={path} end={path==='/'} className={()=>location.pathname===path.split('#')[0] && (path.includes('#')?location.hash==='#pricing':!location.hash)?'active':''}>{label}</NavLink>)}</nav><Link className="button button-small nav-cta" to="/contact">Start a Project <ArrowUpRight size={16}/></Link><button className="mobile-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.nav className="mobile-nav" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} aria-label="Mobile navigation">{nav.map(([label,path])=><NavLink key={path} to={path} end={path==='/'} className={()=>location.pathname===path.split('#')[0] && (path.includes('#')?location.hash==='#pricing':!location.hash)?'active':''}>{label}<ArrowUpRight size={16}/></NavLink>)}<Link className="button" to="/contact">Start a Project <ArrowUpRight size={16}/></Link></motion.nav>}</AnimatePresence></header> }
export function Footer() { return <footer className="footer"><div className="wrap"><div className="footer-main"><div className="footer-brand"><Logo light/><p>Thoughtful websites. Clear pricing. A real team to talk to.</p><Link to="/about">Get to know Webstead <ArrowUpRight size={14}/></Link><div className="socials"><a href="https://www.instagram.com/webstead.in/" aria-label="Instagram">ig</a></div></div><div><h4>Explore</h4>{nav.map(([n,p])=><Link key={p} to={p}>{n}</Link>)}</div><div><h4>Services</h4>{services.map(s=><Link key={s.id} to={`/services#${s.id}`}>{s.title}</Link>)}</div><div><h4>Contact</h4><a href="mailto:webstead.in@gmail.com">webstead.in@gmail.com</a><a href="tel:+919845432516">+91 98454 32516</a><a href="tel:+919544288151">+91 95442 88151</a><Link className="footer-contact" to="/contact">Send an enquiry <ArrowUpRight size={15}/></Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Webstead. All rights reserved.</span><Link to="/privacy">Privacy</Link><a href="https://www.instagram.com/webstead.in/">Instagram <ArrowUpRight size={14}/></a></div></div></footer> }
export function Button({to='/contact',children,secondary=false,...props}) { return <Link to={to} className={`button ${secondary?'button-secondary':''}`} {...props}>{children}<ArrowUpRight size={17}/></Link> }
export function SectionTitle({eyebrow,title,description,light=false}) { return <div className={`section-title ${light?'light':''}`}><span className="eyebrow"><i/>{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div> }
export const techIcons={React:Code2,'Node.js':Server,MongoDB:Database,Express:Workflow,JavaScript:Braces,TypeScript:FileCode2,'Next.js':Layers3,'Tailwind CSS':Wind,Figma:Figma,Git:GitBranch,AWS:Cloud}
const stageIcons=[BriefcaseBusiness,Store,BadgeCheck]
export function PortfolioPreview(){return <div className="portfolio-preview"><div className="preview-kicker"><span>WEBSTEAD / SELECTED WORK</span><span>LIVE PROJECTS ↗</span></div><div className="preview-list">{projects.slice(0,3).map((p,i)=>{const Icon=stageIcons[i];return <a href={p.liveUrl} target="_blank" rel="noreferrer" className="preview-project" key={p.id}><span className="preview-index">0{i+1}</span><span className="preview-icon"><Icon size={22}/></span><span className="preview-name"><b>{p.title}</b><small>{p.category}</small></span><span className="preview-description">{p.description}</span><ArrowUpRight className="preview-arrow" size={19}/></a>})}</div><div className="preview-foot"><span>RECENT WORK · 2025—26</span><span>DESIGNED TO MOVE FORWARD</span></div></div>}
export function PageHero({eyebrow,title,description,compact=false}) { return <section className={`page-hero ${compact?'page-hero-compact':''}`}><div className="wrap"><div className="eyebrow"><i/>{eyebrow}</div><h1>{title}</h1><p>{description}</p><div className="hero-rule"><span/><span>WEBSTEAD · DIGITAL PARTNER</span><span/></div></div></section> }
export function FinalCTA(){return <section className="simple-contact-cta"><div className="wrap simple-contact-row"><div><span className="eyebrow"><i/>YOUR BUSINESS COULD BE NEXT</span><h2>Let�s build a website you�re proud to share.</h2><p>Tell us your idea and budget. We�ll help you find the right starting point.</p></div><div className="simple-contact-actions"><Button>Get my website quote</Button><a className="button button-secondary" href="https://wa.me/919845432516" target="_blank" rel="noreferrer"><WhatsAppIcon size={21}/> Chat on WhatsApp</a></div></div></section>}
export function Stat({value,label}) { return <div className="stat"><strong>{value}</strong><span>{label}</span></div> }
export function ProjectModal({project,onClose}) { useEffect(()=>{if(!project)return;const f=e=>e.key==='Escape'&&onClose();window.addEventListener('keydown',f);document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',f);document.body.style.overflow=''}},[project,onClose]);return <AnimatePresence>{project&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}><motion.section className="case-modal" initial={{y:24,opacity:0}} animate={{y:0,opacity:1}} exit={{y:16,opacity:0}} onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="case-title"><button className="modal-close" onClick={onClose} aria-label="Close case study"><X/></button><img src={project.image} alt={`${project.title} project concept`} /><div className="case-copy"><span className="eyebrow"><i/>CONCEPT PROJECT · {project.category.toUpperCase()}</span><h2 id="case-title">{project.title}</h2><p>{project.description}</p><div className="case-columns"><div><h3>The brief</h3><p>A concept project created to demonstrate a considered digital experience for this industry.</p></div><div><h3>Our approach</h3><p>We shaped the structure, interface and responsive direction around clear customer journeys.</p></div><div><h3>Project status</h3><p>Illustrative portfolio placeholder. Client and performance outcomes to be added when verified.</p></div></div><div className="tag-row">{project.technologies.map(t=><span key={t}>{t}</span>)}</div></div></motion.section></motion.div>}</AnimatePresence> }

